### ISSUE TITLE
two npm packages, one repo, ???

### ISSUE THREAD

**Issue by ungoldman** [koopjs/koop-osm#1]
- https://www.npmjs.com/package/koop-osm (updated 15 days ago)
- https://www.npmjs.com/package/koop-osm-provider (updated a year ago)

Neither of which link to this repo (updated 5 months ago)... what's going on?

**Comment by chelm** [comment]
Hey @ngoldman the two packages were my fault I should have removed koop-osm-provider from NPM. I just removed it now. `koop-osm` is the right one and its just missing info in the package.json. I'll fix that. 

The duplicate npm package was due to a renaming and refactor of the provider pattern on a whole and I'm trying not to have `koop-*-provider` in the name of packages.

**Comment by ungoldman** [comment]
okay thanks, just trying to get a handle on all the koop-\* projects in the wild and bring them under one umbrella so we can collaborate on standardizing, maintaining, etc

**Comment by ungoldman** [comment]
Marking this as resolved.
